version: '2'
services:
  geoffrey:
    image: tadamo/geoffrey
    build:
      context: .
    container_name: geoffrey
  geoffrey-dev-perl:
    extends:
      service: geoffrey
    environment:
      FILE: /Users/tadamo/test/perl.pl
    volumes:
      - .:/usr/local/bin/geoffrey
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/tadamo/test/perl.pl:/Users/tadamo/test/perl.pl
    command: formatter
