version: '2'
services:
  geoffrey:
    image: tadamo/geoffrey
    build:
      context: .
    container_name: geoffrey
  ###################################################################
  ###################################################################
  ###################################################################
  geoffrey-formatter-dev-perl:
    extends:
      service: geoffrey
    environment:
      FILE: $PWD/samples/perl.pl
    volumes:
      - .:/usr/local/bin/geoffrey
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/samples/perl.pl:$PWD/samples/perl.pl
    command: formatter
  geoffrey-formatter-dev-text:
    extends:
      service: geoffrey
    environment:
      FILE: $PWD/samples/text.txt
    volumes:
      - .:/usr/local/bin/geoffrey
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/samples/text.txt:$PWD/samples/text.txt
    command: formatter
