#!/usr/bin/env bash
#set -ex

file_type=$(language-type $FILE)
if [[ -z "${file_type}" ]]; then
    echo "No file type determined for $FILE."
    exit
fi

format_commands=$(config | jq -rcM ".$file_type.formatter")
if [ "$format_commands" = "null" ]; then
    echo "No format configured for $file_type."
    exit
fi

echo "Running the $file_type formatter on: $FILE"
for formatter_row_config in $(echo $format_commands | jq -rcM '.[] | @base64'); do
    formatter_row=$(echo $formatter_row_config | base64 --decode)
    image=$(echo $formatter_row | jq -rcM '.image')
    entrypoint=$(echo $formatter_row | jq -rcM '.entrypoint')
    command=$(echo $formatter_row | jq -rcM '.command')
    docker pull $image
    file_in_container="/tmp/$FILE"
    docker_run="docker run --rm -v $FILE:$file_in_container --entrypoint=$entrypoint $image $command $file_in_container"
    echo $docker_run
    file_formatted=$($docker_run)
    echo "$file_formatted" > $FILE
done
echo "Formatting done of: $FILE"
