#!/usr/bin/env bash
#set -ex
#file=/Users/tadamo/test/perl.pl && docker run --rm -v $(pwd):/usr/local/bin/geoffrey -v $file:$file -e FILE=$file tadamo/geoffrey formatter

file_type=$(language-type $FILE)
format_commands=$(cat $GEOFFREY_CONFIG | jq -rcM ".$file_type.formatter")
for formatter_row_config in $(echo $format_commands | jq -rcM '.[] | @base64'); do
    formatter_row=$(echo $formatter_row_config | base64 --decode)
    image=$(echo $formatter_row | jq -rcM '.image')
    entrypoint=$(echo $formatter_row | jq -rcM '.entrypoint')
    command=$(echo $formatter_row | jq -rcM '.command')
    docker pull $image > /dev/null
    file_formatted=$(docker run -v $FILE:$FILE --entrypoint="$entrypoint" $image $command $FILE)
    echo "$file_formatted" > $FILE
done
